service: image-resizing-python

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1
  tracing: 
    apiGateway: true
    lambda: true 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
        - s3:*
      Resource: '*'

package:
  patterns:
    - '!node_modules/**'
    - '!layers/**'
    - '!.venv/**'
    - '!__pycache__/**'
    - '!.ipynb_checkpoints/**'
    - '!(*).ipynb'
    - '${opt:stage}/**'

functions:
  resize:
    handler: ${opt:stage}/handler.process_image
    memorySize: 512
    timeout: 10
#    tracing: Active
    environment:
      BUCKET: resized-images-python-kg001
      REGION: eu-west-1
    events:
      - http:
          path: /{size}/{image}
          method: get

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: "non-linux"
