service: image-resizing-python

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

layers:
  ImageResizeLayer:
    path: layers
    name: ${self:service}-${opt:stage}-ImgResizelayer
    compatibleRuntimes:
      - python3.11

package:
  patterns:
    - '!node_modules/**'
    - '!layers/**'
    - '!.venv/**'
    - '!__pycache__/**'
    - '!.ipynb_checkpoints/**'
    - '!(*).ipynb'
    - '${opt:stage}/**'

functions:
  resize:
    handler: ${opt:stage}/handler.process_image
    memorySize: 512
    timeout: 10
    environment:
      BUCKET: resized-images-python-kg001
      REGION: eu-west-1
    events:
      - http:
          path: /{size}/{image}
          method: get
    layers:
      - !Ref ImageResizeLayerLambdaLayer

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: "non-linux"
